### ISSUE TITLE
bug: テンプレート3Dmodelが取得できない

### ISSUE THREAD

**Issue by mitsuYashi** [Misoten-B/airship-backend#123]
get: `/v1/users/three_dimentionals`
下記のレスポンス。swaggerでも同様。
![image](https://github.com/Misoten-B/airship-backend/assets/73920580/31f5d715-cffe-4b7f-b931-edd3cfe40a04)

post: `/v1/users/three_dimentionals`
また、アップロードはうまくできているようで、Azureコンテナでも確認できているが、取得できない。

**Comment by nakamura0907** [comment]
@mitsuYashi 
結局これは解決？
